### PR TITLE
Pulp multi version support

### PR DESCRIPTION
**Pull request by actionjack**
Hi Kris,

I've integrated pulp-v1 and pulp-v2 into a single module.
There should be no real change to how you use it at the moment ie. just use "include pulp" to use the pulp version 1 functionality.

The only thing I didn't fix up was the use of a pulp version 1 yum repo, I think you probably use one internally so I didn't want to do anything there yet.

Cheers

-Martin

### CODE REVIEW

**Comment by bigon** [comment]
Hi Kris,

The code looks good to me, except maybe the embedded yumrepo definition

Cheers

**Comment by actionjack** [comment]
I can make that an optional setting with it defaulting to off/on depending on what's required.

**Comment by bigon** [comment]
Hi,

I think that might be nice

Thanks again for your code :)

**Comment by KrisBuytaert** [comment]
Martin, yeah having an optional setting to configure the yum repo would make it great !

**Comment by actionjack** [comment]
Ok yumrepo definition is now optional, it's also easy to add v1 support if needed.

**Pull request merged**
